### ISSUE TITLE
Not listed on PAUSE

### ISSUE THREAD

**Issue by rohanc** [jhthorsen/mojolicious-plugin-ical#2]
I can't install this module from CPAN at the moment:

```
$ cpanm Mojolicious::Plugin::Ical
! Finding Mojolicious::Plugin::Ical on cpanmetadb failed.
! Finding Mojolicious::Plugin::Ical () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Mojolicious::Plugin::Ical
```

Apparently it's supposed to appear in https://cpan.metacpan.org/modules/02packages.details.txt
https://metacpan.org/about/missing_modules

**Comment by jhthorsen** [comment]
@rohanc: I wouldn't mind transferring this project to you. Is that ok?

**Comment by rohanc** [comment]
I'll give that some thought. I sent an email to your cpan email address.

**Comment by jhthorsen** [comment]
It was surprisingly easy to do, so I just pushed it to CPAN now 👍
